name: Test Snowflake CLI Connection

on:
  workflow_dispatch:
  push:

jobs:
  snowflake-connection-test:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SF_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
      SNOWFLAKE_HOST: ${{ secrets.SF_HOST }}
      SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SF_KAY_RAW }}
      SNOWFLAKE_AUTHENTICATOR: "SNOWFLAKE_JWT"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI using snowflakedb/snowflake-cli-action
        uses: snowflakedb/snowflake-cli-action@v1.5

      - name: Test snow connection
        run: |
          snow connection test -x

